"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class motion_data(object):
    __slots__ = ["linear_speed", "angle"]

    def __init__(self):
        self.linear_speed = 0.0
        self.angle = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(motion_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.linear_speed, self.angle))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motion_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motion_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motion_data()
        self.linear_speed, self.angle = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motion_data in parents: return 0
        tmphash = (0xcf793a9e87d3b256) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motion_data._packed_fingerprint is None:
            motion_data._packed_fingerprint = struct.pack(">Q", motion_data._get_hash_recursive([]))
        return motion_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

